-- Catálogo autorizado por Tropicleta, 29/09/2026. Actualización única; conserva IDs, reservas y estado de publicación.
INSERT INTO service_categories (slug,name,description,sort) VALUES ('mantenciones','Mantenciones','Revisión y puesta a punto general de tu bicicleta, desde lo básico hasta el desarme completo.',0) ON CONFLICT (slug) DO NOTHING;
--> statement-breakpoint
INSERT INTO service_categories (slug,name,description,sort) VALUES ('suspensiones','Suspensiones','Servicio a horquillas y amortiguadores de aire y resorte para que tu bici absorba como el primer día.',1) ON CONFLICT (slug) DO NOTHING;
--> statement-breakpoint
INSERT INTO service_categories (slug,name,description,sort) VALUES ('transmision','Transmisión','Cadena, cassette, platos y cambios funcionando finos, sin saltos ni ruidos.',2) ON CONFLICT (slug) DO NOTHING;
--> statement-breakpoint
INSERT INTO service_categories (slug,name,description,sort) VALUES ('frenos','Frenos','Frenos mecánicos e hidráulicos: ajuste, purga, pastillas y discos.',3) ON CONFLICT (slug) DO NOTHING;
--> statement-breakpoint
INSERT INTO service_categories (slug,name,description,sort) VALUES ('ruedas','Ruedas','Tubeless, centrado, pinchazos y armado de ruedas.',4) ON CONFLICT (slug) DO NOTHING;
--> statement-breakpoint
INSERT INTO service_categories (slug,name,description,sort) VALUES ('ejes','Ejes y rodamientos','Centro, dirección y bujes girando suaves y sin juego.',5) ON CONFLICT (slug) DO NOTHING;
--> statement-breakpoint
INSERT INTO service_categories (slug,name,description,sort) VALUES ('scooters','Scooters eléctricos','Diagnóstico y mantención de scooters eléctricos: frenos, neumáticos y ajustes.',6) ON CONFLICT (slug) DO NOTHING;
--> statement-breakpoint
INSERT INTO service_categories (slug,name,description,sort) VALUES ('retiro-entrega','Retiro y entrega','Retiramos y entregamos tu bici en sectores definidos de Tierra Amarilla, Paipote y Copiapó.',7) ON CONFLICT (slug) DO NOTHING;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,featured,sort) VALUES ('mantencion-completa',(SELECT id FROM service_categories WHERE slug='mantenciones'),'Mantención completa','Servicio de todos los ejes, ajuste de frenos y cambios, limpieza de bicicleta y transmisión, y lubricación. No incluye suspensión, sangrado de frenos ni ajustes de horquilla.','Atención con coordinación previa. Consulta disponibilidad y plazo al agendar.','[]'::jsonb,50000,false,NULL,true,0) ON CONFLICT (slug) DO UPDATE SET name=excluded.name, summary=excluded.summary, description=excluded.description, includes=excluded.includes, price=excluded.price, price_from=excluded.price_from, duration=NULL;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,featured,sort) VALUES ('mantencion-basica',(SELECT id FROM service_categories WHERE slug='mantenciones'),'Mantención básica','Mantención básica de tu bicicleta. Coordinamos el alcance y el plazo al realizar el diagnóstico gratuito.','Atención con coordinación previa. Consulta disponibilidad y plazo al agendar.','[]'::jsonb,35000,false,NULL,false,1) ON CONFLICT (slug) DO UPDATE SET name=excluded.name, summary=excluded.summary, description=excluded.description, includes=excluded.includes, price=excluded.price, price_from=excluded.price_from, duration=NULL;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,featured,sort) VALUES ('ajuste-inicial',(SELECT id FROM service_categories WHERE slug='mantenciones'),'Ajuste inicial','Puesta a punto inicial de tu bicicleta, con coordinación previa.','Atención con coordinación previa. Consulta disponibilidad y plazo al agendar.','[]'::jsonb,35000,false,NULL,false,2) ON CONFLICT (slug) DO UPDATE SET name=excluded.name, summary=excluded.summary, description=excluded.description, includes=excluded.includes, price=excluded.price, price_from=excluded.price_from, duration=NULL;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,featured,sort) VALUES ('servicio-al-cuadro',(SELECT id FROM service_categories WHERE slug='mantenciones'),'Servicio al cuadro','Servicio al cuadro de tu bicicleta. Consulta compatibilidad y alcance durante el diagnóstico.','Atención con coordinación previa. Consulta disponibilidad y plazo al agendar.','[]'::jsonb,25000,false,NULL,false,3) ON CONFLICT (slug) DO UPDATE SET name=excluded.name, summary=excluded.summary, description=excluded.description, includes=excluded.includes, price=excluded.price, price_from=excluded.price_from, duration=NULL;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,featured,sort) VALUES ('limpieza-bicicleta-transmision',(SELECT id FROM service_categories WHERE slug='mantenciones'),'Limpieza de bicicleta + transmisión','Limpieza de bicicleta y transmisión para seguir rodando.','Atención con coordinación previa. Consulta disponibilidad y plazo al agendar.','[]'::jsonb,15000,false,NULL,false,4) ON CONFLICT (slug) DO UPDATE SET name=excluded.name, summary=excluded.summary, description=excluded.description, includes=excluded.includes, price=excluded.price, price_from=excluded.price_from, duration=NULL;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,featured,sort) VALUES ('servicio-completo-horquilla',(SELECT id FROM service_categories WHERE slug='suspensiones'),'Horquilla de aire','Mantención y ajuste completo de horquilla de aire.','Atención con coordinación previa. Consulta disponibilidad y plazo al agendar.','[]'::jsonb,50000,false,NULL,false,5) ON CONFLICT (slug) DO UPDATE SET name=excluded.name, summary=excluded.summary, description=excluded.description, includes=excluded.includes, price=excluded.price, price_from=excluded.price_from, duration=NULL;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,featured,sort) VALUES ('servicio-basico-horquilla',(SELECT id FROM service_categories WHERE slug='suspensiones'),'Servicio de botellas','Limpieza, cambio de sellos y aceite.','Atención con coordinación previa. Consulta disponibilidad y plazo al agendar.','[]'::jsonb,35000,false,NULL,false,6) ON CONFLICT (slug) DO UPDATE SET name=excluded.name, summary=excluded.summary, description=excluded.description, includes=excluded.includes, price=excluded.price, price_from=excluded.price_from, duration=NULL;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,featured,sort) VALUES ('horquilla-mecanica',(SELECT id FROM service_categories WHERE slug='suspensiones'),'Horquilla mecánica','Limpieza, lubricación y ajuste completo.','Atención con coordinación previa. Consulta disponibilidad y plazo al agendar.','[]'::jsonb,25000,false,NULL,false,7) ON CONFLICT (slug) DO UPDATE SET name=excluded.name, summary=excluded.summary, description=excluded.description, includes=excluded.includes, price=excluded.price, price_from=excluded.price_from, duration=NULL;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,featured,sort) VALUES ('servicio-amortiguador',(SELECT id FROM service_categories WHERE slug='suspensiones'),'Servicio de shock','Mantención y ajuste completo del amortiguador.','Atención con coordinación previa. Consulta disponibilidad y plazo al agendar.','[]'::jsonb,50000,false,NULL,false,8) ON CONFLICT (slug) DO UPDATE SET name=excluded.name, summary=excluded.summary, description=excluded.description, includes=excluded.includes, price=excluded.price, price_from=excluded.price_from, duration=NULL;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,featured,sort) VALUES ('ajuste-de-cambios',(SELECT id FROM service_categories WHERE slug='transmision'),'Sincronización de cambios','Sincronización de cambios, ajuste de cableado y rectificación de postiza.','Atención con coordinación previa. Consulta disponibilidad y plazo al agendar.','[]'::jsonb,15000,false,NULL,false,9) ON CONFLICT (slug) DO UPDATE SET name=excluded.name, summary=excluded.summary, description=excluded.description, includes=excluded.includes, price=excluded.price, price_from=excluded.price_from, duration=NULL;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,featured,sort) VALUES ('servicio-pata-de-cambio',(SELECT id FROM service_categories WHERE slug='transmision'),'Servicio de pata de cambio','Desarme, limpieza y lubricación de pata de cambio y rectificación de postiza.','Atención con coordinación previa. Consulta disponibilidad y plazo al agendar.','[]'::jsonb,15000,false,NULL,false,10) ON CONFLICT (slug) DO UPDATE SET name=excluded.name, summary=excluded.summary, description=excluded.description, includes=excluded.includes, price=excluded.price, price_from=excluded.price_from, duration=NULL;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,featured,sort) VALUES ('limpieza-ultrasonica-encerado',(SELECT id FROM service_categories WHERE slug='transmision'),'Limpieza ultrasónica + encerado de cadena','Servicio premium de limpieza ultrasónica y encerado de cadena: menos fricción y mayor vida útil.','Atención con coordinación previa. Consulta disponibilidad y plazo al agendar.','[]'::jsonb,35000,false,NULL,true,11) ON CONFLICT (slug) DO UPDATE SET name=excluded.name, summary=excluded.summary, description=excluded.description, includes=excluded.includes, price=excluded.price, price_from=excluded.price_from, duration=NULL;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,featured,sort) VALUES ('armado-de-rueda',(SELECT id FROM service_categories WHERE slug='ruedas'),'Armado de rueda','Centrado y tensado. Valor del servicio: $20.000; rayos se cobran aparte.','Atención con coordinación previa. Consulta disponibilidad y plazo al agendar.','[]'::jsonb,20000,false,NULL,false,12) ON CONFLICT (slug) DO UPDATE SET name=excluded.name, summary=excluded.summary, description=excluded.description, includes=excluded.includes, price=excluded.price, price_from=excluded.price_from, duration=NULL;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,featured,sort) VALUES ('tubeless-completo',(SELECT id FROM service_categories WHERE slug='ruedas'),'Tubeless completo','Servicio tubeless completo. Incluye cinta y líquido.','Atención con coordinación previa. Consulta disponibilidad y plazo al agendar.','[]'::jsonb,20000,false,NULL,true,13) ON CONFLICT (slug) DO UPDATE SET name=excluded.name, summary=excluded.summary, description=excluded.description, includes=excluded.includes, price=excluded.price, price_from=excluded.price_from, duration=NULL;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,featured,sort) VALUES ('recarga-liquido',(SELECT id FROM service_categories WHERE slug='ruedas'),'Recarga / inyección de líquido','Recarga de líquido para cámara y tubeless.','Atención con coordinación previa. Consulta disponibilidad y plazo al agendar.','[]'::jsonb,7000,false,NULL,false,14) ON CONFLICT (slug) DO UPDATE SET name=excluded.name, summary=excluded.summary, description=excluded.description, includes=excluded.includes, price=excluded.price, price_from=excluded.price_from, duration=NULL;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,featured,sort) VALUES ('eje-delantero',(SELECT id FROM service_categories WHERE slug='ejes'),'Servicio de eje delantero','Servicio de eje delantero para un rodar más suave.','Atención con coordinación previa. Consulta disponibilidad y plazo al agendar.','[]'::jsonb,8000,false,NULL,false,15) ON CONFLICT (slug) DO UPDATE SET name=excluded.name, summary=excluded.summary, description=excluded.description, includes=excluded.includes, price=excluded.price, price_from=excluded.price_from, duration=NULL;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,featured,sort) VALUES ('eje-trasero',(SELECT id FROM service_categories WHERE slug='ejes'),'Servicio de eje trasero','Servicio de eje trasero de tu bicicleta.','Atención con coordinación previa. Consulta disponibilidad y plazo al agendar.','[]'::jsonb,8000,false,NULL,false,16) ON CONFLICT (slug) DO UPDATE SET name=excluded.name, summary=excluded.summary, description=excluded.description, includes=excluded.includes, price=excluded.price, price_from=excluded.price_from, duration=NULL;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,featured,sort) VALUES ('mantencion-de-direccion',(SELECT id FROM service_categories WHERE slug='ejes'),'Servicio de eje de dirección','Servicio del eje de dirección de tu bicicleta.','Atención con coordinación previa. Consulta disponibilidad y plazo al agendar.','[]'::jsonb,8000,false,NULL,false,17) ON CONFLICT (slug) DO UPDATE SET name=excluded.name, summary=excluded.summary, description=excluded.description, includes=excluded.includes, price=excluded.price, price_from=excluded.price_from, duration=NULL;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,featured,sort) VALUES ('servicio-nucleo',(SELECT id FROM service_categories WHERE slug='ejes'),'Servicio de núcleo','Servicio de núcleo para seguir rodando.','Atención con coordinación previa. Consulta disponibilidad y plazo al agendar.','[]'::jsonb,10000,false,NULL,false,18) ON CONFLICT (slug) DO UPDATE SET name=excluded.name, summary=excluded.summary, description=excluded.description, includes=excluded.includes, price=excluded.price, price_from=excluded.price_from, duration=NULL;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,featured,sort) VALUES ('mantencion-de-centro',(SELECT id FROM service_categories WHERE slug='ejes'),'Servicio de eje motor','Servicio de eje motor de tu bicicleta.','Atención con coordinación previa. Consulta disponibilidad y plazo al agendar.','[]'::jsonb,10000,false,NULL,false,19) ON CONFLICT (slug) DO UPDATE SET name=excluded.name, summary=excluded.summary, description=excluded.description, includes=excluded.includes, price=excluded.price, price_from=excluded.price_from, duration=NULL;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,featured,sort) VALUES ('frenos-scooter',(SELECT id FROM service_categories WHERE slug='scooters'),'Ajuste de freno de scooter','Valor por freno. Revisión, tensión de cable y posición de pastillas.','Atención con coordinación previa. Consulta disponibilidad y plazo al agendar.','[]'::jsonb,8000,false,NULL,false,20) ON CONFLICT (slug) DO UPDATE SET name=excluded.name, summary=excluded.summary, description=excluded.description, includes=excluded.includes, price=excluded.price, price_from=excluded.price_from, duration=NULL;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,featured,sort) VALUES ('pinchazo-scooter',(SELECT id FROM service_categories WHERE slug='scooters'),'Cambio de cámara de scooter','Cambio de cámara para scooter eléctrico. Atención con coordinación previa.','Atención con coordinación previa. Consulta disponibilidad y plazo al agendar.','[]'::jsonb,10000,false,NULL,false,21) ON CONFLICT (slug) DO UPDATE SET name=excluded.name, summary=excluded.summary, description=excluded.description, includes=excluded.includes, price=excluded.price, price_from=excluded.price_from, duration=NULL;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,featured,sort) VALUES ('liquido-scooter',(SELECT id FROM service_categories WHERE slug='scooters'),'Recarga / inyección de líquido de scooter','Para neumáticos tubeless cuando corresponda.','Atención con coordinación previa. Consulta disponibilidad y plazo al agendar.','[]'::jsonb,7000,false,NULL,false,22) ON CONFLICT (slug) DO UPDATE SET name=excluded.name, summary=excluded.summary, description=excluded.description, includes=excluded.includes, price=excluded.price, price_from=excluded.price_from, duration=NULL;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,featured,sort) VALUES ('retiro-y-entrega',(SELECT id FROM service_categories WHERE slug='retiro-entrega'),'Retiro y entrega de bicicletas','Tierra Amarilla: solo retiro o entrega $3.000, ambos $5.000. Paipote: solo retiro o entrega $8.000, ambos $15.000. Copiapó: solo retiro o entrega $12.000, ambos $20.000. Coordinación previa; consulta por otras zonas.','Atención con coordinación previa. Consulta disponibilidad y plazo al agendar.','[]'::jsonb,3000,true,NULL,false,23) ON CONFLICT (slug) DO UPDATE SET name=excluded.name, summary=excluded.summary, description=excluded.description, includes=excluded.includes, price=excluded.price, price_from=excluded.price_from, duration=NULL;
