-- Correcciones autorizadas por Tropicleta, 30/09/2026. Conserva IDs e historial. No modifica retiro y entrega.
UPDATE service_categories SET name='Mantenciones y servicios generales',description='Mantenciones y servicios generales de bicicleta.',sort=0 WHERE slug='mantenciones';
--> statement-breakpoint
UPDATE service_categories SET name='Frenos y cambios',description='Ajuste de frenos y cambios, purga y servicio de pata de cambio.',sort=1 WHERE slug='frenos';
--> statement-breakpoint
UPDATE service_categories SET name='Horquillas y suspensiones',description='Servicios de horquillas y shock.',sort=2 WHERE slug='suspensiones';
--> statement-breakpoint
UPDATE service_categories SET name='Ruedas y sistema tubeless',description='Servicios de ruedas y líquido sellante tubeless para bicicletas y scooters.',sort=3 WHERE slug='ruedas';
--> statement-breakpoint
UPDATE service_categories SET name='Ejes, dirección, núcleo y motor',description='Servicios de ejes, dirección, núcleo y motor.',sort=4 WHERE slug='ejes';
--> statement-breakpoint
UPDATE service_categories SET name='Servicios para scooter',description='Solo realizamos parchados, cambio de cámara, inyección de líquido sellante tubeless y ajuste de frenos. El líquido sellante se selecciona en Ruedas y sistema tubeless.',sort=5 WHERE slug='scooters';
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,active,sort) VALUES ('mantencion-completa',(SELECT id FROM service_categories WHERE slug='mantenciones'),'Mantención completa','Servicio de todos los ejes, ajuste de frenos y cambios, limpieza de bicicleta y transmisión, y lubricación. No incluye suspensión, sangrado de frenos ni ajustes de horquilla.','Servicio de todos los ejes, ajuste de frenos y cambios, limpieza de bicicleta y transmisión, y lubricación. No incluye suspensión, sangrado de frenos ni ajustes de horquilla.','[]'::jsonb,50000,false,NULL,true,0) ON CONFLICT (slug) DO UPDATE SET category_id=excluded.category_id,name=excluded.name,summary=excluded.summary,description=excluded.description,includes=excluded.includes,price=excluded.price,price_from=false,duration=NULL,sort=excluded.sort;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,active,sort) VALUES ('mantencion-basica',(SELECT id FROM service_categories WHERE slug='mantenciones'),'Mantención básica','Mantención básica de tu bicicleta.','Mantención básica de tu bicicleta.','[]'::jsonb,35000,false,NULL,true,1) ON CONFLICT (slug) DO UPDATE SET category_id=excluded.category_id,name=excluded.name,summary=excluded.summary,description=excluded.description,includes=excluded.includes,price=excluded.price,price_from=false,duration=NULL,sort=excluded.sort;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,active,sort) VALUES ('ajuste-inicial',(SELECT id FROM service_categories WHERE slug='mantenciones'),'Ajuste inicial','Puesta a punto inicial de tu bicicleta.','Puesta a punto inicial de tu bicicleta.','[]'::jsonb,35000,false,NULL,true,2) ON CONFLICT (slug) DO UPDATE SET category_id=excluded.category_id,name=excluded.name,summary=excluded.summary,description=excluded.description,includes=excluded.includes,price=excluded.price,price_from=false,duration=NULL,sort=excluded.sort;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,active,sort) VALUES ('mantencion-ebike',(SELECT id FROM service_categories WHERE slug='mantenciones'),'Mantención de bicicleta eléctrica','Mantención de tu bicicleta eléctrica.','Mantención de tu bicicleta eléctrica.','[]'::jsonb,65000,false,NULL,true,3) ON CONFLICT (slug) DO UPDATE SET category_id=excluded.category_id,name=excluded.name,summary=excluded.summary,description=excluded.description,includes=excluded.includes,price=excluded.price,price_from=false,duration=NULL,sort=excluded.sort;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,active,sort) VALUES ('servicio-al-cuadro',(SELECT id FROM service_categories WHERE slug='mantenciones'),'Servicio del cuadro','Servicio del cuadro de tu bicicleta.','Servicio del cuadro de tu bicicleta.','[]'::jsonb,25000,false,NULL,true,4) ON CONFLICT (slug) DO UPDATE SET category_id=excluded.category_id,name=excluded.name,summary=excluded.summary,description=excluded.description,includes=excluded.includes,price=excluded.price,price_from=false,duration=NULL,sort=excluded.sort;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,active,sort) VALUES ('armado-bicicleta-nueva',(SELECT id FROM service_categories WHERE slug='mantenciones'),'Armado de bicicleta nueva','Armado y ajuste de tu bicicleta nueva.','Armado y ajuste de tu bicicleta nueva.','[]'::jsonb,35000,false,NULL,true,5) ON CONFLICT (slug) DO UPDATE SET category_id=excluded.category_id,name=excluded.name,summary=excluded.summary,description=excluded.description,includes=excluded.includes,price=excluded.price,price_from=false,duration=NULL,sort=excluded.sort;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,active,sort) VALUES ('limpieza-bicicleta-transmision',(SELECT id FROM service_categories WHERE slug='mantenciones'),'Limpieza de bicicleta más transmisión','Limpieza de bicicleta y transmisión.','Limpieza de bicicleta y transmisión.','[]'::jsonb,15000,false,NULL,true,6) ON CONFLICT (slug) DO UPDATE SET category_id=excluded.category_id,name=excluded.name,summary=excluded.summary,description=excluded.description,includes=excluded.includes,price=excluded.price,price_from=false,duration=NULL,sort=excluded.sort;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,active,sort) VALUES ('limpieza-ultrasonica-encerado',(SELECT id FROM service_categories WHERE slug='mantenciones'),'Limpieza ultrasónica más encerado','Limpieza ultrasónica y encerado de cadena.','Limpieza ultrasónica y encerado de cadena.','[]'::jsonb,35000,false,NULL,true,7) ON CONFLICT (slug) DO UPDATE SET category_id=excluded.category_id,name=excluded.name,summary=excluded.summary,description=excluded.description,includes=excluded.includes,price=excluded.price,price_from=false,duration=NULL,sort=excluded.sort;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,active,sort) VALUES ('ajuste-frenos-cambios',(SELECT id FROM service_categories WHERE slug='frenos'),'Ajuste de frenos y cambios','Ajuste de frenos y cambios de tu bicicleta.','Ajuste de frenos y cambios de tu bicicleta.','[]'::jsonb,20000,false,NULL,true,8) ON CONFLICT (slug) DO UPDATE SET category_id=excluded.category_id,name=excluded.name,summary=excluded.summary,description=excluded.description,includes=excluded.includes,price=excluded.price,price_from=false,duration=NULL,sort=excluded.sort;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,active,sort) VALUES ('ajuste-frenos-mecanicos',(SELECT id FROM service_categories WHERE slug='frenos'),'Ajuste de frenos mecánicos o hidráulicos','Incluye cambio o rectificación de disco cuando corresponda; no se ofrece como servicio separado.','Incluye cambio o rectificación de disco cuando corresponda; no se ofrece como servicio separado.','[]'::jsonb,7000,false,NULL,true,9) ON CONFLICT (slug) DO UPDATE SET category_id=excluded.category_id,name=excluded.name,summary=excluded.summary,description=excluded.description,includes=excluded.includes,price=excluded.price,price_from=false,duration=NULL,sort=excluded.sort;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,active,sort) VALUES ('purga-frenos-hidraulicos',(SELECT id FROM service_categories WHERE slug='frenos'),'Purga de frenos','Purga de frenos.','Purga de frenos.','[]'::jsonb,15000,false,NULL,true,10) ON CONFLICT (slug) DO UPDATE SET category_id=excluded.category_id,name=excluded.name,summary=excluded.summary,description=excluded.description,includes=excluded.includes,price=excluded.price,price_from=false,duration=NULL,sort=excluded.sort;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,active,sort) VALUES ('ajuste-de-cambios',(SELECT id FROM service_categories WHERE slug='frenos'),'Sincronización de cambios','Sincronización de cambios, ajuste de cableado y rectificación de postiza.','Sincronización de cambios, ajuste de cableado y rectificación de postiza.','[]'::jsonb,15000,false,NULL,true,11) ON CONFLICT (slug) DO UPDATE SET category_id=excluded.category_id,name=excluded.name,summary=excluded.summary,description=excluded.description,includes=excluded.includes,price=excluded.price,price_from=false,duration=NULL,sort=excluded.sort;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,active,sort) VALUES ('servicio-pata-de-cambio',(SELECT id FROM service_categories WHERE slug='frenos'),'Servicio de pata de cambio','Desarme, limpieza y lubricación de pata de cambio y rectificación de postiza.','Desarme, limpieza y lubricación de pata de cambio y rectificación de postiza.','[]'::jsonb,15000,false,NULL,true,12) ON CONFLICT (slug) DO UPDATE SET category_id=excluded.category_id,name=excluded.name,summary=excluded.summary,description=excluded.description,includes=excluded.includes,price=excluded.price,price_from=false,duration=NULL,sort=excluded.sort;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,active,sort) VALUES ('servicio-basico-horquilla',(SELECT id FROM service_categories WHERE slug='suspensiones'),'Servicio de botellas','Limpieza, cambio de sellos y aceite.','Limpieza, cambio de sellos y aceite.','[]'::jsonb,35000,false,NULL,true,13) ON CONFLICT (slug) DO UPDATE SET category_id=excluded.category_id,name=excluded.name,summary=excluded.summary,description=excluded.description,includes=excluded.includes,price=excluded.price,price_from=false,duration=NULL,sort=excluded.sort;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,active,sort) VALUES ('servicio-completo-horquilla',(SELECT id FROM service_categories WHERE slug='suspensiones'),'Servicio completo de horquilla de aire','Mantención y ajuste completo de horquilla de aire.','Mantención y ajuste completo de horquilla de aire.','[]'::jsonb,50000,false,NULL,true,14) ON CONFLICT (slug) DO UPDATE SET category_id=excluded.category_id,name=excluded.name,summary=excluded.summary,description=excluded.description,includes=excluded.includes,price=excluded.price,price_from=false,duration=NULL,sort=excluded.sort;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,active,sort) VALUES ('horquilla-mecanica',(SELECT id FROM service_categories WHERE slug='suspensiones'),'Servicio completo de horquilla mecánica','Limpieza, lubricación y ajuste completo.','Limpieza, lubricación y ajuste completo.','[]'::jsonb,25000,false,NULL,true,15) ON CONFLICT (slug) DO UPDATE SET category_id=excluded.category_id,name=excluded.name,summary=excluded.summary,description=excluded.description,includes=excluded.includes,price=excluded.price,price_from=false,duration=NULL,sort=excluded.sort;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,active,sort) VALUES ('servicio-amortiguador',(SELECT id FROM service_categories WHERE slug='suspensiones'),'Servicio de shock','Mantención y ajuste completo del amortiguador.','Mantención y ajuste completo del amortiguador.','[]'::jsonb,50000,false,NULL,true,16) ON CONFLICT (slug) DO UPDATE SET category_id=excluded.category_id,name=excluded.name,summary=excluded.summary,description=excluded.description,includes=excluded.includes,price=excluded.price,price_from=false,duration=NULL,sort=excluded.sort;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,active,sort) VALUES ('tubeless-completo',(SELECT id FROM service_categories WHERE slug='ruedas'),'Servicio completo de ruedas tubeless','Incluye cinta y líquido sellante.','Incluye cinta y líquido sellante.','[]'::jsonb,20000,false,NULL,true,17) ON CONFLICT (slug) DO UPDATE SET category_id=excluded.category_id,name=excluded.name,summary=excluded.summary,description=excluded.description,includes=excluded.includes,price=excluded.price,price_from=false,duration=NULL,sort=excluded.sort;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,active,sort) VALUES ('recarga-liquido',(SELECT id FROM service_categories WHERE slug='ruedas'),'Recarga o inyección de líquido sellante tubeless','Para bicicletas y scooters con sistema tubeless.','Para bicicletas y scooters con sistema tubeless.','[]'::jsonb,7000,false,NULL,true,18) ON CONFLICT (slug) DO UPDATE SET category_id=excluded.category_id,name=excluded.name,summary=excluded.summary,description=excluded.description,includes=excluded.includes,price=excluded.price,price_from=false,duration=NULL,sort=excluded.sort;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,active,sort) VALUES ('centrado-de-rueda',(SELECT id FROM service_categories WHERE slug='ruedas'),'Centrado de rueda','Centrado de rueda.','Centrado de rueda.','[]'::jsonb,10000,false,NULL,true,19) ON CONFLICT (slug) DO UPDATE SET category_id=excluded.category_id,name=excluded.name,summary=excluded.summary,description=excluded.description,includes=excluded.includes,price=excluded.price,price_from=false,duration=NULL,sort=excluded.sort;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,active,sort) VALUES ('armado-de-rueda',(SELECT id FROM service_categories WHERE slug='ruedas'),'Armado de rueda','No incluye rayos; se cobran por separado.','No incluye rayos; se cobran por separado.','[]'::jsonb,20000,false,NULL,true,20) ON CONFLICT (slug) DO UPDATE SET category_id=excluded.category_id,name=excluded.name,summary=excluded.summary,description=excluded.description,includes=excluded.includes,price=excluded.price,price_from=false,duration=NULL,sort=excluded.sort;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,active,sort) VALUES ('eje-delantero',(SELECT id FROM service_categories WHERE slug='ejes'),'Servicio de eje delantero','Servicio de eje delantero; incluye el trabajo de buje correspondiente.','Servicio de eje delantero; incluye el trabajo de buje correspondiente.','[]'::jsonb,8000,false,NULL,true,21) ON CONFLICT (slug) DO UPDATE SET category_id=excluded.category_id,name=excluded.name,summary=excluded.summary,description=excluded.description,includes=excluded.includes,price=excluded.price,price_from=false,duration=NULL,sort=excluded.sort;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,active,sort) VALUES ('eje-trasero',(SELECT id FROM service_categories WHERE slug='ejes'),'Servicio de eje trasero','Servicio de eje trasero; incluye el trabajo de buje correspondiente.','Servicio de eje trasero; incluye el trabajo de buje correspondiente.','[]'::jsonb,8000,false,NULL,true,22) ON CONFLICT (slug) DO UPDATE SET category_id=excluded.category_id,name=excluded.name,summary=excluded.summary,description=excluded.description,includes=excluded.includes,price=excluded.price,price_from=false,duration=NULL,sort=excluded.sort;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,active,sort) VALUES ('servicio-nucleo',(SELECT id FROM service_categories WHERE slug='ejes'),'Servicio de núcleo','Servicio de núcleo.','Servicio de núcleo.','[]'::jsonb,10000,false,NULL,true,23) ON CONFLICT (slug) DO UPDATE SET category_id=excluded.category_id,name=excluded.name,summary=excluded.summary,description=excluded.description,includes=excluded.includes,price=excluded.price,price_from=false,duration=NULL,sort=excluded.sort;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,active,sort) VALUES ('mantencion-de-centro',(SELECT id FROM service_categories WHERE slug='ejes'),'Servicio de motor','Servicio de motor.','Servicio de motor.','[]'::jsonb,10000,false,NULL,true,24) ON CONFLICT (slug) DO UPDATE SET category_id=excluded.category_id,name=excluded.name,summary=excluded.summary,description=excluded.description,includes=excluded.includes,price=excluded.price,price_from=false,duration=NULL,sort=excluded.sort;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,active,sort) VALUES ('mantencion-de-direccion',(SELECT id FROM service_categories WHERE slug='ejes'),'Servicio de eje de dirección','Servicio del eje de dirección.','Servicio del eje de dirección.','[]'::jsonb,10000,false,NULL,true,25) ON CONFLICT (slug) DO UPDATE SET category_id=excluded.category_id,name=excluded.name,summary=excluded.summary,description=excluded.description,includes=excluded.includes,price=excluded.price,price_from=false,duration=NULL,sort=excluded.sort;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,active,sort) VALUES ('parchado-scooter',(SELECT id FROM service_categories WHERE slug='scooters'),'Parchados de scooter','Parchados de scooter.','Parchados de scooter.','[]'::jsonb,NULL,false,NULL,true,26) ON CONFLICT (slug) DO UPDATE SET category_id=excluded.category_id,name=excluded.name,summary=excluded.summary,description=excluded.description,includes=excluded.includes,price=excluded.price,price_from=false,duration=NULL,sort=excluded.sort;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,active,sort) VALUES ('pinchazo-scooter',(SELECT id FROM service_categories WHERE slug='scooters'),'Cambio de cámara de scooter','Cambio de cámara de scooter.','Cambio de cámara de scooter.','[]'::jsonb,NULL,false,NULL,true,27) ON CONFLICT (slug) DO UPDATE SET category_id=excluded.category_id,name=excluded.name,summary=excluded.summary,description=excluded.description,includes=excluded.includes,price=excluded.price,price_from=false,duration=NULL,sort=excluded.sort;
--> statement-breakpoint
INSERT INTO services (slug,category_id,name,summary,description,includes,price,price_from,duration,active,sort) VALUES ('frenos-scooter',(SELECT id FROM service_categories WHERE slug='scooters'),'Ajuste de frenos de scooter','Ajuste de frenos de scooter.','Ajuste de frenos de scooter.','[]'::jsonb,7000,false,NULL,true,28) ON CONFLICT (slug) DO UPDATE SET category_id=excluded.category_id,name=excluded.name,summary=excluded.summary,description=excluded.description,includes=excluded.includes,price=excluded.price,price_from=false,duration=NULL,sort=excluded.sort;
--> statement-breakpoint
UPDATE services SET active=false,featured=false WHERE slug IN ('revision-pre-competencia','cambio-de-cadena','cambio-transmision-completa','cambio-de-pastillas','reparacion-de-pinchazo','cambio-de-neumatico','mantencion-de-bujes','mantencion-scooter','configuracion-sag','cambio-de-disco','liquido-scooter');
